version: "3.7"
services:

    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: docker.io/library/pscibisz-db-web
        container_name: db-app
        restart: unless-stopped
        environment:
            WEBROOT: '/var/www/html/public'
        ports:
            - 8000:80
#        volumes:
#            - ./:/var/www/html
        networks:
            - net-db

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        command: [ "--default-authentication-plugin=mysql_native_password" ]
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: db_app
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: password
            MYSQL_USER: admin
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - net-db

    s3-app:
        build:
            context: ./../s3-app
            dockerfile: Dockerfile
        image: s3
        container_name: s3-app
        restart: unless-stopped
        environment:
            URL_APP_DB: http://nginx_app
        volumes:
            - ./../s3-app/:/var/www/html
        networks:
            - net-db

    s3-nginx:
        image: nginx:1.17-alpine
        container_name: s3-nginx
        restart: unless-stopped
        ports:
            - 8001:80
        volumes:
            - ./../s3-app/:/var/www/html
            - ./../s3-app/nginx:/etc/nginx/conf.d
        networks:
            - net-db

    test:
        image: public.ecr.aws/ablachowicz-public-ecr-reg/pscibisz-db-nginx:latest

networks:
    net-db:
        driver: bridge
